services:
  webui:
    image: ghcr.io/itsleeo/ksc-web-ui:dev
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env.webui
  api:
    image: ghcr.io/itsleeo/ksc-shop-api:dev
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env.api
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - db_data_1:/var/lib/postgresql/data

volumes:     
  db_data_1:
